In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2],[3, 4]]) # order

In [4]:
a = np.arange(1, 10) # range와 똑같이 볼 수 있다.
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

copy가 도대체 뭐냐

In [5]:
a = b = [1, 2, 3] # 뮤터블 
a.append(4)
b

[1, 2, 3, 4]

In [1]:
a = b = [1, 2, 3] # 뮤터블 
c = a.copy() # 이렇게 하면 카피가 되서, 값이 바뀌지 않는다.
a.append(4)
c

[1, 2, 3]

In [2]:
d = a[:] # 이것도 카피 방식이다
a.append(5)
d

[1, 2, 3, 4]

In [3]:
a = b = [[1,2],[3,4]]
c = a[:]
c[0][0] = 4

In [4]:
print(c)
print(a) # 안에있는 얘들까지 카피가 되어야 하는데 안되어있다.

[[4, 2], [3, 4]]
[[4, 2], [3, 4]]


In [9]:
import copy

a = b = [[1,2],[3,4]]
c = copy.deepcopy(a)
c[0][0] = 4

In [6]:
print(c)
print(a) 

[[4, 2], [3, 4]]
[[1, 2], [3, 4]]


그렇다면 넘파이에서 카피는? 기본적인 카피가 딥카피이다. ★★★

In [8]:
a = np.array([[1, 2], [3, 4]])
b = a # 카피가 안 된 경우
b[0][0] = 4

print(a)
print(b)

[[4 2]
 [3 4]]
[[4 2]
 [3 4]]


In [9]:
a = np.array([[1, 2], [3, 4]])
b = a.copy() # 이렇게 카피를 하면 기본적으로 딥카피가 되어버린다.
b[0][0] = 4

print(a)
print(b)

[[1 2]
 [3 4]]
[[4 2]
 [3 4]]


원본을 놔두고 나머지것들을 실험해야 하니까 이런 카피기법을 쓴다. 어쨋든 기본적인 nparray이기 때문에 깊게 들어가는 경우가 많기 때문에 딥카피가 기본이다. 

그럼 스왈로우 카피는?? view라고 해주면 된다.

In [10]:
a = np.array([[1,2],[3,4]])
b = a.view()
b[0,0] = 5
print(a)
print(b)

[[5 2]
 [3 4]]
[[5 2]
 [3 4]]


In [12]:
a = np.array([[1,2],[3,4]])
b = a.copy()
b[0,0] = 5
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 2]
 [3 4]]


### linespace

In [14]:
a = np.linspace(1, 100) # 처음부터 끝까지 디폴트로 50등분 해준다.
b = np.logspace(1, 10, num = 5) # 값의 범위를 줄여준다.

print(a)
print(b)

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


### 시퀀스 (인덱싱, 슬라이싱 가능)

파이썬보다 기능이 확대되었다.

1. 콤마
2. 짝을 이루는 콤마
3. 마스킹
4. 펜시 인덱싱
5. 조건이 있는 펜시 인덱싱

### 1. 콤마 방식: a[0, 0]

In [15]:
a = np.array([[1,2],[3,4]])
a[1,0] # a[0][1]과 동일하다. 파이썬에서는 안 된다.

3

### 2. 짝을 이루는 콤마

In [17]:
a

array([[1, 2],
       [3, 4]])

In [18]:
a[(1, 1), [0, 1]] # (1,0), (1,1)이 출력된다.

array([3, 4])

### 3. 마스킹 (True, False)

True, False를 넣는 것을 마스킹 기법이라고 한다.<br>
필요한 데이터를 뽑아낼 때 빼고는 안 쓰긴 하는데 이왕 나왔으니까 해본다.

In [25]:
cond = a>2
cond

array([[False, False],
       [ True,  True]])

In [26]:
a[cond]

array([3, 4])

### 4. 펜시 인덱싱: 대괄호 2개! [[__]]

In [21]:
a[[0]] # 행기준으로 다 뽑아낼 때 쓴다. 펜시 인덱싱이라고 한다. 괄호가 2개인 것

array([[1, 2]])

In [22]:
a = np.array(np.arange(1, 26)).reshape(5,5)

In [23]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 이 인덱싱 슬라이싱은 왜 쓰나? 

파이썬과 비교도 안되게 속도가 빠르기 때문이다. 헤더가 붙어있는데, 이것 때문에 하나하나 체크를 안해도 되기 때문이다. <br>
파이썬은 링크드 리스트 기반이라서 유연하긴 하지만, 메모리가 지멋대로이다.

#### opencv를 쓰는 이유

1. 영상처리는 pil이라는 애가 있는데, 케라스가 이 필로우 기반이라서 공부를 해야 한다.
2. 워낙 잘 만들어놨다. 많은 기능을 제공한다.
3. 4버전부터 딥러닝을 훨신 더 강화했다.
4. GPU를 지원한다.

단점은

1. 한글처리가 안된다. (유니코드)

#### 스트라이드

 - 원소 1개당 메모리가 할당되어 있는 방식을 말하는데, 이것으로 인해 개별 원소들에 빠르게 접근할 수 있다.
 - int64에서 itemsize는 8로 나누면 되므로, 8이다. 이 8이 곧 1개 원소에 할당이 된다.
 - 스트라이드 개념은 for문을 다 돌리지 않아도 되고, 성큼성큼 요소들 사이를 건너뛴다. 그래서 속도가 빠르다. 그렇기 때문에 리덕션 리덕션 하기 쉽다. 리덕션은 값을 하나로 축약하는 것이다.
 - (행을넘어가는데 필요한 itemsize 합, 원소 1개를 넘어가는데 필요한 itemsize합) -> 이게 stride 이다.

 - reshape도 이 스트라이드를 바꿔주기 때문에 빠르다. 거의 리얼타임으로 바뀌어진다.

In [27]:
a = np.array([[1,2],[3,4]])
b = np.array([[[1, 2], [3, 4]]])
print(a.dtype)
a.strides # 행넘어가는데 몇 메모리가 필요하고, 열넘어가는데 몇 메모리가 필요한가. 8로 나눠서 1개 원소당 필요한 메모리(아이템사이즈).
b.strides

int32


(16, 8, 4)

In [28]:
a = np.arange(9).reshape(3,3)
# a.dtype
a.itemsize

4

In [29]:
a.strides

(12, 4)

#### 메모리를 저장하는 방식

1. C방식: 옆으로
2. 포트란 방식: 아래로

넘파이는 C 방식이다.

#### axis

1. 0은 행마다.
2. 1은 열마다.

In [30]:
a = np.arange(0, 100).reshape(20,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [32]:
a.mean(axis = 0) # 열평균

array([47.5, 48.5, 49.5, 50.5, 51.5])

In [33]:
a.mean(axis = 1) # 행평균

array([ 2.,  7., 12., 17., 22., 27., 32., 37., 42., 47., 52., 57., 62.,
       67., 72., 77., 82., 87., 92., 97.])

햇갈리면, 0이면 0을 가리고, 1이면 1을 가려라

### reshape와 resize

1. reshape는 모양을 맞춰줘야 하지만, resize는 꼭 shape 안 맞춰도 된다.
2. reshape는 임뮤터블이지만, resize는 상관없다.

In [74]:
a = np.arange(20).reshape(4,5) # 임뮤터블이라서 값을 바꿀려면 재할당해야한다. 이것처럼. (4, -1)과 같다.
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

reshape -1이라고 하면 자동으로 맞춰주는데, 이건 0보다 작을 경우 자동으로 맞춰준다는 의미이므로 -2, -3 다 된다.

In [34]:
a = np.resize(a, (4, 6)) # 모양도 바꾸고, 크기도 줄어들고 늘어나게 할 수 있다. -1 하면 크기가 하나씩 줄어든다.
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### 함수형 방식과 메소드 방식

In [35]:
np.add(3, 4) # 함수형 방식. function 방식
np.array([3]).add(4) # 메소드 방식

AttributeError: 'numpy.ndarray' object has no attribute 'add'

In [37]:
a = np.array([1, 2])
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

우리는 reshape만 쓸거다. resize는 굉장히 위험하다.

언제 쓰나면, flatten할 때 쓴다.

In [85]:
a.reshape(-1, a.size)

array([[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1,
        2, 3]])

### ravel과 flatten

1. ravel은 view이다. 바뀔 때 같이 바뀌면 view이다.
2. flatten은 copy. deep copy인 것이다.

그래서 원본이 바뀌면 안되니까, flatten만 쓰게 된다.

In [39]:
a = np.arange(100).reshape(20,5)
b = a.ravel() # 라벨은 view 이다.
a[0, 0] = 100

print(a)
print(b)

[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [ 40  41  42  43  44]
 [ 45  46  47  48  49]
 [ 50  51  52  53  54]
 [ 55  56  57  58  59]
 [ 60  61  62  63  64]
 [ 65  66  67  68  69]
 [ 70  71  72  73  74]
 [ 75  76  77  78  79]
 [ 80  81  82  83  84]
 [ 85  86  87  88  89]
 [ 90  91  92  93  94]
 [ 95  96  97  98  99]]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99]


In [40]:
a.flatten() # flatten은 copy다. 원본 바뀌면 안 되니까 flatten만 쓰게 되는 것이다.

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])

넘파이에서는 값 변화시킬 때 주의해야 한다. 원본까지 바뀌기 때문에, 조심해서 써야 한다.

In [43]:
x = [1, 2, 3, 4, 5]
b = x[:3]
b[0] = 100
b

[100, 2, 3]

### Broadcasting

like 붙어있는 애들 쓰면 브로드캐스팅 효과가 난다.

★★★그런데 브로드캐스팅보다 속도가 빠르다. 별로 속도 차이는 안나나보다...

In [93]:
np.array([1, 2, 3]) + 1

array([2, 3, 4])

In [94]:
import tensorflow as tf

x = tf.constant([1, 2, 3])
x+3

<tf.Tensor: id=2, shape=(3,), dtype=int32, numpy=array([4, 5, 6])>

### Shape

넘파이는 기본적으로 2방향으로 쪼갠다. 행으로 쪼개고, 열로 쪼갠다.

In [41]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
np.split(a, (1,3)) # 1행보다 작은거 하나, 1행, 3행 중간 하나, 3행보다 큰거 하나.

[array([[0, 1, 2, 3, 4]]), array([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19]])]

항상 axis가 복잡할 때는 , h, v 등이 붙는 함수들이 있다.

In [100]:
np.split(a, (2, 2))

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([], shape=(0, 5), dtype=int32),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [101]:
np.hsplit(a, (2, 2)) # 자르는 방향으로 생각하면 안되고, 나오는 결과물을 봐라. 수평으로 이어진다. 그래서 hsplit이다.

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16]]), array([], shape=(4, 0), dtype=int32), array([[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19]])]

In [106]:
a, _, b = np.vsplit(a, (2, 2)) # 마지막 결과물이 수직으로 쌓여 있는 거니까, vsplit이다.
print(a, b)

[[0 1 2 3 4]
 [5 6 7 8 9]] [[10 11 12 13 14]
 [15 16 17 18 19]]


### 데이터 붙이는 것 2개

1. concatenate: shpae가 변경이 안된다.
2. stack: new axis를 하나 더 만들어서 붙여준다.

둘다 쓸데가 있다.

In [43]:
a = np.arange(20).reshape(2,-1)
a, b = np.hsplit(a,2)
print(a)
print(b)

[[ 0  1  2  3  4]
 [10 11 12 13 14]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [44]:
np.concatenate((a, b), axis = 1) # axis = 1은 행 결과

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [45]:
np.vstack((a, b)) # 마지막 결과가 수직으로 쌓인다.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [110]:
np.hstack((a, b)) # 마지막 결과가 수평으로 쌓인다.

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

이런식으로 과정으로 생각하지말고, 마지막에 나오는 결과가 무엇이 될것이냐로 보는게 편하다. ★★★

In [54]:
c = np.stack((a, b), axis = 0)
c

array([[[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]],

       [[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]]])

In [56]:
c.shape

(2, 2, 5)

In [58]:
# new axis에 따라서 해준다. 그래서 골치아파서 내일.
np.newaxis # 리턴값이 None이다.