In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([1, 2, 3])
a

<tf.Tensor: id=0, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

1. shape이 같아야 연산이 가능하다.
2. dtype이 중요한 이유는?.. 별로 없다.

In [3]:
a.shape

TensorShape([3])

In [6]:
a.dtype

tf.int32

In [8]:
tf.zeros((2, 3))

<tf.Tensor: id=4, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [9]:
tf.ones((2, 3)) # 뉴럴네트워크를 해야 하기 때문에 넘파이보다 너 많은 것들이 들어간다.

<tf.Tensor: id=7, shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [12]:
tf.ones((2, 2)) * 6

<tf.Tensor: id=15, shape=(2, 2), dtype=float32, numpy=
array([[6., 6.],
       [6., 6.]], dtype=float32)>

In [4]:
tf.eye(4)

<tf.Tensor: id=4, shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [5]:
tf.identity(4) # 텐서플로의 아이덴티티는 다르다.

<tf.Tensor: id=5, shape=(), dtype=int32, numpy=4>

In [18]:
tf.fill((10, 10), 3)

<tf.Tensor: id=23, shape=(10, 10), dtype=int32, numpy=
array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])>

### equality vs identity

 - equelity: 값이 같은 것
 - identity: 값과 메모리까지 같은 것