In [1]:
import time
import numpy as np
from PIL import Image as pil_image
import tensorflow as tf
from tensorflow.keras.preprocessing.image import save_img
from tensorflow.keras import layers
from tensorflow.keras.applications import vgg16
from tensorflow.keras import backend as K

print(tf.__version__)

2.0.0


### normalize 이해하기

In [2]:
def normalize(x):
    """utility function to normalize a tensor.

    # Arguments
        x: An input tensor.

    # Returns
        The normalized input tensor.
    """
    return x / (K.sqrt(K.mean(K.square(x))) + K.epsilon())

In [5]:
with tf.compat.v1.Session() as sess:
    a = sess.run(normalize(np.array([1., 2., 3., 4., 5.])))
    print(a)

[0.30151134 0.60302267 0.90453401 1.20604534 1.50755668]


In [4]:
a = np.array([1, 2, 3, 4, 5])
a / np.sqrt(np.mean(a * a))

array([0.30151134, 0.60302269, 0.90453403, 1.20604538, 1.50755672])

### deprocess_image 이해하기

In [6]:
def deprocess_image(x):
    """utility function to convert a float array into a valid uint8 image.

    # Arguments
        x: A numpy-array representing the generated image.

    # Returns
        A processed numpy-array, which could be used in e.g. imshow.
    """
    # normalize tensor: center on 0., ensure std is 0.25
    x -= x.mean()
    x /= (x.std() + K.epsilon())
    x *= 0.25

    # clip to [0, 1]
    x += 0.5
    x = np.clip(x, 0, 1)

    # convert to RGB array
    x *= 255
    if K.image_data_format() == 'channels_first':
        x = x.transpose((1, 2, 0))
    x = np.clip(x, 0, 255).astype('uint8')
    return x

In [7]:
np.clip(np.array([1, 2, 3, 4, 5, 6]), 2, 4)

array([2, 2, 3, 4, 4, 4])